language: generic
dist: xenial
sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=nwchem-openmpi

script:
  - docker build --tag "$IMAGE_NAME" .

after_script:
  - docker-compose -f docker-compose.travis.yml up
