version: '3'
services:
  nwchem:
    image: 'marcindulak/nwchem-openmpi:latest'
    volumes:
      - './myjob:/mnt:rw'
    command:
      - /bin/bash
      - -c
      - |
        . /etc/profile.d/modules.sh
        module use /usr/share/modulefiles
        module load mpi/openmpi-x86_64
        cd /mnt
        mpiexec --allow-run-as-root -np 2 nwchem_openmpi h2.nw > h2.out
